CREATE TABLE arqui_servicio (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	nombre TEXT UNIQUE NOT NULL,
	descripcion TEXT NOT NULL,
	fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE arqui_proyecto (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	nombre TEXT UNIQUE NOT NULL,
	descripcion TEXT NOT NULL,
	fotos TEXT DEFAULT NULL, 
	fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
